# Generated by Django 5.2.8 on 2025-11-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nombre del proyecto', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del proyecto', null=True)),
                ('location', models.CharField(blank=True, help_text='Ubicación del proyecto', max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='País', max_length=100, null=True)),
                ('region', models.CharField(blank=True, help_text='Región/Departamento', max_length=100, null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Zona horaria', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el proyecto está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('owner', models.ForeignKey(blank=True, help_text='Propietario del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
