# Generated by Django 5.2.8 on 2025-11-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrograph',
            name='design_storm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='watershed',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rainfalldata',
            name='watershed',
        ),
        migrations.DeleteModel(
            name='DesignStorm',
        ),
        migrations.DeleteModel(
            name='Hydrograph',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='RainfallData',
        ),
        migrations.DeleteModel(
            name='Watershed',
        ),
    ]
