# Generated by Django 5.2.8 on 2025-11-09 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la cuenca', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción de la cuenca', null=True)),
                ('area_hectareas', models.FloatField(db_index=True, help_text='Área en hectáreas')),
                ('tc_horas', models.FloatField(help_text='Tiempo de concentración en horas')),
                ('nc_scs', models.IntegerField(blank=True, help_text='Número de curva SCS (30-100)', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitud (grados decimales)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitud (grados decimales)', null=True)),
                ('elevation_m', models.FloatField(blank=True, help_text='Elevación en metros', null=True)),
                ('c_racional', models.FloatField(blank=True, help_text='Coeficiente de escorrentía para Método Racional (0-1)', null=True)),
                ('extra_metadata', models.JSONField(blank=True, help_text='Metadata adicional en formato JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece la cuenca', on_delete=django.db.models.deletion.CASCADE, related_name='watersheds', to='projects.project')),
            ],
            options={
                'verbose_name': 'Cuenca',
                'verbose_name_plural': 'Cuencas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'name'], name='watersheds__project_95bad8_idx')],
            },
        ),
    ]
