# Generated by Django 5.2.8 on 2025-11-09 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watersheds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignStorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la tormenta', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción de la tormenta', null=True)),
                ('return_period_years', models.IntegerField(db_index=True, help_text='Período de retorno (Tr) en años')),
                ('duration_hours', models.FloatField(db_index=True, help_text='Duración de la tormenta en horas')),
                ('total_rainfall_mm', models.FloatField(help_text='Lluvia total en milímetros')),
                ('distribution_type', models.CharField(choices=[('alternating_block', 'Alternating Block'), ('chicago', 'Chicago'), ('sidle', 'Sidle'), ('custom', 'Custom')], default='alternating_block', help_text='Tipo de distribución temporal de la lluvia', max_length=50)),
                ('initial_abstraction_mm', models.FloatField(blank=True, help_text='Abstracción inicial (Ia) en mm, típicamente 0.2*S', null=True)),
                ('storage_parameter_mm', models.FloatField(blank=True, help_text='Parámetro de almacenamiento (S) en mm, calculado como (25400/NC - 254)', null=True)),
                ('time_step_minutes', models.IntegerField(default=5, help_text='Intervalo de tiempo en minutos')),
                ('extra_metadata', models.JSONField(blank=True, help_text='Metadata adicional en formato JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('watershed', models.ForeignKey(help_text='Cuenca a la que pertenece la tormenta', on_delete=django.db.models.deletion.CASCADE, related_name='design_storms', to='watersheds.watershed')),
            ],
            options={
                'verbose_name': 'Tormenta de Diseño',
                'verbose_name_plural': 'Tormentas de Diseño',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hydrograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo del hidrograma', max_length=255, null=True)),
                ('method', models.CharField(choices=[('rational', 'Método Racional'), ('scs_unit_hydrograph', 'SCS Unit Hydrograph'), ('synth_unit_hydro', 'Synthetic Unit Hydrograph')], db_index=True, help_text='Método de cálculo utilizado', max_length=50)),
                ('peak_discharge_m3s', models.FloatField(db_index=True, help_text='Caudal máximo en m³/s')),
                ('peak_discharge_lps', models.FloatField(blank=True, help_text='Caudal máximo en L/s', null=True)),
                ('time_to_peak_minutes', models.FloatField(blank=True, help_text='Tiempo al pico en minutos', null=True)),
                ('total_runoff_mm', models.FloatField(blank=True, help_text='Escorrentía total en mm', null=True)),
                ('total_runoff_m3', models.FloatField(blank=True, help_text='Escorrentía total en m³', null=True)),
                ('volume_hm3', models.FloatField(blank=True, help_text='Volumen total en hm³', null=True)),
                ('hydrograph_data', models.JSONField(help_text='Serie temporal del hidrograma: [{time_min, discharge_m3s, cumulative_volume_m3}, ...]')),
                ('rainfall_excess_mm', models.FloatField(blank=True, help_text='Lluvia en exceso (lluvia neta) en mm', null=True)),
                ('infiltration_total_mm', models.FloatField(blank=True, help_text='Infiltración total en mm', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el cálculo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('design_storm', models.ForeignKey(help_text='Tormenta de diseño utilizada', on_delete=django.db.models.deletion.CASCADE, related_name='hydrographs', to='hydrology.designstorm')),
            ],
            options={
                'verbose_name': 'Hidrograma',
                'verbose_name_plural': 'Hidrogramas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True, help_text='Fecha del evento de lluvia')),
                ('return_period_years', models.IntegerField(blank=True, help_text='Período de retorno estimado (años)', null=True)),
                ('duration_hours', models.FloatField(blank=True, help_text='Duración del evento en horas', null=True)),
                ('total_rainfall_mm', models.FloatField(help_text='Lluvia total en mm')),
                ('rainfall_series', models.JSONField(help_text='Serie temporal de lluvia: [{time_min, intensity_mm_h, cumulative_mm}, ...]')),
                ('source', models.CharField(blank=True, help_text='Fuente de datos (DNM, IMFIA, sensor local, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el evento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro')),
                ('watershed', models.ForeignKey(help_text='Cuenca donde se midió la lluvia', on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_data', to='watersheds.watershed')),
            ],
            options={
                'verbose_name': 'Datos de Lluvia',
                'verbose_name_plural': 'Datos de Lluvia',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddIndex(
            model_name='designstorm',
            index=models.Index(fields=['watershed', 'return_period_years'], name='hydrology_d_watersh_0dac03_idx'),
        ),
        migrations.AddIndex(
            model_name='hydrograph',
            index=models.Index(fields=['design_storm', 'method'], name='hydrology_h_design__a76c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='rainfalldata',
            index=models.Index(fields=['watershed', 'event_date'], name='hydrology_r_watersh_19c093_idx'),
        ),
    ]
