# Generated by Django 5.2.8 on 2025-11-09 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designstorm',
            name='peak_position_ratio',
            field=models.FloatField(default=0.5, help_text='Posición del pico como ratio (0.0-1.0). 0.5 = centro, 0.3 = inicio, 0.7 = final', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
